### ISSUE TITLE
fixing the new trakt sort order

### ISSUE THREAD

**Issue by kodistuff1** [Colossal1/script.module.covenant#20]
The new Trakt Progress sorting method was pushed a bit early, and I'm seeing references on reddit to the sort order sometimes being wrong (not just different, but actually wrong.)

It's hard to be certain, but stale cached episode data (without the new '_last_watched' and '_sort_key') is likely the cause. Clearing the cache should be a one-time fix, but does require user action.

I propose the following, which wipes cache.db entirely each time s.m.c is updated. Add this to the end of cache.py...

```
def _cache_version_changed():
    import xbmcaddon, os
    try:
        curVersion = xbmcaddon.Addon('script.module.covenant').getAddonInfo('version')
        versionFile = os.path.join(control.dataPath, 'cache.v')
        fh = open(versionFile, 'a+b')
        oldVersion = fh.read()
        if curVersion != oldVersion:
            fh.seek(0)
            fh.write(curVersion)
            fh.truncate()
            fh.close()
            return True
    except:
        pass
    return False

if _cache_version_changed():
    cache_clear()
    control.infoDialog(control.lang(32052).encode('utf-8'), sound=True, icon='INFO')
```

Blowing away the cache might be a bit aggressive, but it is simpler and does future-proof things somewhat. A different solution might just be to delete any cache created by 1.00.008 or earlier.

Now that the cache is clean, I'd also suggest replacing '_sort_key' in episodes.py with something a bit more descriptive, such as '_recently' (as it is a blend of Trakt's 'Recently Aired' and 'Recently Watched').

**Comment by Kr1ss-XD** [comment]
Thx @kodistuff1  ,
Auto-clearing the cache might actually be a good thing to do.
Will look into it.

**Comment by kodistuff1** [comment]
Updated version: improved code, just wipes the cache from versions before 1.00.009

```
"""
    The cache.v file tracks the last version of s.m.c to access cache.db
    If s.m.c knows that that version creates a stale or incompatible cache,
    then clear the cache.

    1.00.009 wipes the cache to fix the new Trakt Progress sorting method.
"""
def _cache_version_check():
    import os
    versionFile = os.path.join(control.dataPath, 'cache.v')
    try:
        fh = open(versionFile, 'rb')
        oldVersion = fh.read()
        fh.close()
    except:
        oldVersion = '0'
    try:
        curVersion = control.addon('script.module.covenant').getAddonInfo('version')
        if oldVersion != curVersion:
            fh = open(versionFile, 'wb')
            fh.write(curVersion)
            fh.close()
    except:
        return False
    return ( oldVersion < '1.00.009' or oldVersion > curVersion )

if _cache_version_check():
    id = control.addonInfo('id')
    if id == 'plugin.video.covenant':
        control.infoDialog(control.lang(32052).encode('utf-8'), icon='INFO')
    elif id == 'plugin.video.bennu':
        control.infoDialog('[B]BENNU[/B] : ' + control.lang(30719).encode('utf-8'), icon='INFO')
    else:
        control.infoDialog('Clear cache...')
    cache_clear()
```

**Comment by Colossal1** [comment]
To limit the calls every time the cache.py is imported I would suggest calling it from root. Every time Bennu or Covenant is opened to its main directory the check will be performed. I have also tweatked some elements of the functions like with statments for files to avoid opening and closing. Please tell me what you think and I will push this in the next version if we are all happy.

`"""
    The cache.v file tracks the last version of s.m.c to access cache.db
    If s.m.c knows that that version creates a stale or incompatible cache,
    then clear the cache.

    1.00.009 wipes the cache to fix any issues a new module version could bring.
"""

def _cache_version_check():

    if _find_cache_version():
        cache_clear()
        if control.addonInfo('id') == 'plugin.video.bennu':
            cache_clear_meta()
            cache_clear_providers()
        control.infoDialog(control.lang(32057).encode('utf-8'), sound=True, icon='INFO')
        
def _find_cache_version():

    import os
    versionFile = os.path.join(control.dataPath, 'cache.v')
    try:
        with open(versionFile, 'rb') as fh: oldVersion = fh.read()
    except:
        oldVersion = '0'
    try:
        curVersion = control.addon('script.module.covenant').getAddonInfo('version')
        if oldVersion != curVersion:
            with open(versionFile, 'wb') as fh: fh.write(curVersion)
    except:
        return False
    return ( oldVersion < '1.00.009' or oldVersion > curVersion )`

**Comment by Kr1ss-XD** [comment]
@Colossal1 @kodistuff1 Indeed this would be that would be more elegant.

Have just tested placing the function call in _covenant.py_, line 61f : 
```
from resources.lib.modules import cache
cache._cache_version_check()
```
Tried w/ both smc v1.00.008 and v1.00.009 (Just changed the verion number for test purpose).
Both works like expected (cache is wiped only in 1.00.008).

However, since the method is called from outside, I would suggest to name it `cache_version_check()`, without the trailing underscore.

**Comment by Colossal1** [comment]
Bump to 1.00.009 has this feature. Issue closed.

**Comment by kodistuff1** [comment]
> To limit the calls every time the cache.py is imported I would suggest calling it from root.

Everything I've read says that python only executes the code [the first time a module is imported](https://docs.python.org/2/tutorial/modules.html#more-on-modules) , so doing everything in cache.py will actually limit the calls even more (because not everything imports the cache).

It's also better to show the infoDialog before clearing the cache rather than after, so that the message is on-screen while that's happening.
