### ISSUE TITLE
Quality showing up in HD even though it isn't

### ISSUE THREAD

**Issue by Maston1c** [Colossal1/script.module.covenant#35]
Particularly links from allrls. Maybe from other sources as well? I'm not sure. I ran the code through a debugger and it returns:

`sources = [{'info': 'ALLRLS', 'language': 'en', 'url': u'xxxxxxx', 'debridonly': True, 'direct': False, 'source': 'xxxx.net', 'quality': 'SD'},`

but every link that shows up in Covenant shows 720p even though SD is being returned. Not sure what is going wrong, no idea how to fix it. It seems like it should be correct...

**Comment by Colossal1** [comment]
It is not getting quality from the links but the links seem to be incorrect, i.e. the urls say 720p but they are not.

I will revert the changes back soon.
