### ISSUE TITLE
REAL-DEBRID String and Sources Strings in results page

### ISSUE THREAD

**Issue by Cizzzzz** [Colossal1/script.module.covenant#36]
Would it be possible to reduce the string 'REAL-DEBRID' in the results page to something shorter, such as 'RD'? 
Even the sources could be abbreviated like FileFactory = 'FF', OpenLoad = "OL" etc...
This way the scrolling goes faster, or no scrolling at all, and therefore being able to see the video's file name. Often the file name says it all.
Thx.

**Comment by Colossal1** [comment]
Covenant pulls the strings from URL Resolver so any fork abbreviation would have to be done in covenant.

This would mean all new hosters added to SMU would not be abbreviated and would create extra work for us always playing catch up.

At the moment there is no plan to do this as the current system is automated and always up to date.

**Comment by Cizzzzz** [comment]
Thanks for your reply!
