### ISSUE TITLE
xem integration

### ISSUE THREAD

**Issue by homik** [Colossal1/script.module.covenant#4]
Covenant uses tv shows episodes numbering from trakt which causes that some tv shows sources are loaded incorrectly. Most of the source websites use 'scene' numbering and not 'tvdb'.

Good example of that is American Dad. If you open for example episode form season 13 then what you will get is sources of episodes from season 14. 

This issue can be solved by fixing the number mapping using thexem.de (american dad example http://thexem.de/xem/show/3885)

For API doc see http://thexem.de/doc

**Comment by Colossal1** [comment]
Your PR was merged and included in the 1.00.009 update. Issue closed.
