### ISSUE TITLE
Metalliq exception 

### ISSUE THREAD

**Issue by M-F-B** [Colossal1/script.module.covenant#68]
May you please add plugin.video.metalliq to the exceptions list within Script.Module.Covenant / Control.py as default. 

Everytime the module updates, the exception for Metalliq that I manually add, gets removed. (this lasted just one day this week) 

This exception is needed for the Metalliq widget to work with Covenant.

Thanks guys, hope it gets added soon.

**Comment by Colossal1** [comment]
This is the reason the control exists in the first place.
